### ISSUE TITLE
Add website to dark-sites.config

### ISSUE THREAD

**Issue by oSumAtrIX** [Vendicated/vendicated.dev#3]
Instead of 29308a47ad5f4a31106d97e2f2af88101f54e896 contribute to `dark-sites.config` [here](https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#adding-a-website-that-is-already-dark).

**Comment by Vendicated** [comment]
Thanks for the suggestion (and sorry for responding so late) but sadly I can't, since I'm not following their requirements since I show a light theme if you do not use dark theme:
> The entire website, including all subpages, is dark by default, regardless of the system's preferred color scheme.

Is there any other way to fix dark reader making the site look horrible?

**Comment by oSumAtrIX** [comment]
If you follow the system preference, unfortunately, you can not add your page to the `dark-sites.config` file.
